# Generated by Django 3.2 on 2021-04-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=10),
        ),
    ]
