# Generated by Django 3.2 on 2021-05-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_likes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert')], default='no filter', max_length=50),
        ),
    ]
