# Generated by Django 3.2 on 2021-05-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='action',
        ),
    ]
