# Generated by Django 3.2.2 on 2021-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
