# Generated by Django 3.2.2 on 2021-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20210508_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
